version: '3.8'

services:
  # Next.js Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # environment:
    #   - NODE_ENV=production
    #   - NEXT_PUBLIC_API_BASE_URL=http://157.66.101.198:9000
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
