version: '3.8'

services:
  # Next.js Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # environment:
    #   - NODE_ENV=production
    #   - NEXT_PUBLIC_API_BASE_URL=http://157.66.101.198:9000
    networks:
      - app-network
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    # SSL Certificates (cần mount SSL certificates vào đây)
    # - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
    networks:
      - app-network
    restart: unless-stopped
    environment:
      - DOMAIN=k-network.io

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
