'use client'

import React, { createContext, useContext, useEffect, useState } from 'react'

type Language = 'vi' | 'en'

interface LanguageContextType {
    language: Language
    setLanguage: (lang: Language) => void
    t: (key: string) => string
    mounted: boolean
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Translation data
const translations = {
    vi: {
        // Navigation
        'nav.forex': 'Sàn Forex',
        'nav.news': 'Tin Tức',
        'nav.knowledge': 'Kiến Thức',
        'nav.cryptoBrokers': 'Sàn Crypto',
        'nav.joinTelegram': 'Tham gia Telegram',
        'nav.joinTelegramSubtitle': 'Yêu cầu nâng hoa hồng',


        // Common
        'common.back': 'Quay lại',
        'common.readMore': 'Đọc chi tiết',
        'common.search': 'Tìm kiếm',
        'common.filter': 'Lọc',
        'common.sort': 'Sắp xếp',
        'common.category': 'Danh mục',
        'common.all': 'Tất cả',
        'common.readTime': 'phút',
        'common.previous': 'Trước',
        'common.next': 'Tiếp',
        'common.page': 'Trang',
        'common.of': 'của',
        'common.showing': 'Hiển thị',
        'common.to': 'đến',
        'common.items': 'mục',

        // Home page
        'home.title': 'Danh Sách Sàn Forex Uy Tín',
        'home.subtitle': 'Khám phá các sàn forex hàng đầu với đánh giá chi tiết, so sánh tính năng và link đăng ký trực tiếp',
        'home.searchPlaceholder': 'Tìm kiếm sàn forex...',
        'home.sortByRating': 'Đánh giá cao nhất',
        'home.sortByName': 'Tên A-Z',
        'home.visit': 'Truy cập',
        'home.viewDetails': 'Xem chi tiết',
        'home.regulation': 'Quy định',
        'home.minDeposit': 'Nạp tối thiểu',
        'home.spread': 'Spread',
        'home.noBrokersFound': 'Không tìm thấy sàn forex',
        'home.tryDifferentKeywords': 'Thử tìm kiếm với từ khóa khác',
        'home.welcome': 'Chào mừng đến với K-Network',
        'home.heroTitle': 'Nền tảng tài chính',
        'home.heroTitleHighlight': 'hàng đầu',
        'home.heroSubtitle': 'Khám phá thế giới forex và cryptocurrency với thông tin chính xác, đánh giá chi tiết và công cụ hỗ trợ giao dịch hiệu quả',
        'home.exploreForex': 'Khám phá Forex',
        'home.exploreCrypto': 'Khám phá Crypto',
        'home.stats.forexBrokers': 'Sàn Forex',
        'home.stats.cryptoBrokers': 'Sàn Crypto',
        'home.stats.articles': 'Bài Viết',
        'home.stats.users': 'Người Dùng',
        'home.features.forexTitle': 'Sàn Forex Uy Tín',
        'home.features.forexDesc': 'Khám phá các sàn forex hàng đầu với đánh giá chi tiết, so sánh tính năng và link đăng ký trực tiếp',
        'home.features.cryptoTitle': 'Sàn Crypto Tốt Nhất',
        'home.features.cryptoDesc': 'So sánh và chọn sàn giao dịch cryptocurrency phù hợp nhất với nhu cầu của bạn',
        'home.features.newsTitle': 'Tin Tức Forex Mới Nhất',
        'home.features.newsDesc': 'Cập nhật những tin tức mới nhất về thị trường forex, phân tích kỹ thuật và cơ bản',
        'home.features.knowledgeTitle': 'Kiến Thức Forex',
        'home.features.knowledgeDesc': 'Học hỏi từ cơ bản đến nâng cao về thị trường forex. Xây dựng nền tảng kiến thức vững chắc',
        'home.features.exploreNow': 'Khám phá ngay',
        'home.whyChoose.title': 'Tại sao chọn K-Network?',
        'home.whyChoose.reliable.title': 'Thông tin đáng tin cậy',
        'home.whyChoose.reliable.desc': 'Dữ liệu được cập nhật thường xuyên và kiểm chứng từ các nguồn uy tín',
        'home.whyChoose.fast.title': 'Cập nhật nhanh chóng',
        'home.whyChoose.fast.desc': 'Thông tin thị trường và đánh giá sàn được cập nhật theo thời gian thực',
        'home.whyChoose.community.title': 'Cộng đồng lớn',
        'home.whyChoose.community.desc': 'Hỗ trợ từ cộng đồng trader giàu kinh nghiệm và chuyên gia tài chính',
        'home.cta.title': 'Sẵn sàng bắt đầu hành trình giao dịch?',
        'home.cta.subtitle': 'Tham gia cùng hàng nghìn trader đã thành công với K-Network',
        'home.cta.startForex': 'Bắt đầu với Forex',
        'home.cta.exploreCrypto': 'Khám phá Crypto',
        'home.about.title': 'Về K-Network',
        'home.about.subtitle': 'Chúng tôi là ai và tại sao bạn nên tin tưởng chúng tôi',
        'home.about.description': 'K-Network là nền tảng tài chính hàng đầu tại Việt Nam, chuyên cung cấp thông tin, đánh giá và so sánh các sàn giao dịch forex và cryptocurrency uy tín. Với hơn 5 năm kinh nghiệm trong lĩnh vực tài chính, chúng tôi cam kết mang đến cho bạn những thông tin chính xác và khách quan nhất.',
        'home.about.mission': 'Sứ mệnh của chúng tôi',
        'home.about.missionDesc': 'Giúp người Việt Nam tiếp cận thị trường tài chính toàn cầu một cách an toàn và hiệu quả thông qua việc cung cấp thông tin đáng tin cậy và công cụ hỗ trợ giao dịch.',
        'home.about.vision': 'Tầm nhìn',
        'home.about.visionDesc': 'Trở thành nền tảng tài chính số 1 tại Việt Nam, được tin tưởng bởi hàng triệu nhà đầu tư.',
        'home.services.title': 'Dịch vụ của chúng tôi',
        'home.services.subtitle': 'Tất cả những gì bạn cần để bắt đầu hành trình giao dịch',
        'home.services.brokerReview.title': 'Đánh giá sàn giao dịch',
        'home.services.brokerReview.desc': 'Đánh giá chi tiết và so sánh các sàn forex, crypto uy tín với thông tin minh bạch.',
        'home.services.education.title': 'Giáo dục tài chính',
        'home.services.education.desc': 'Khóa học từ cơ bản đến nâng cao, giúp bạn xây dựng nền tảng kiến thức vững chắc.',
        'home.services.analysis.title': 'Phân tích thị trường',
        'home.services.analysis.desc': 'Tin tức, phân tích kỹ thuật và cơ bản được cập nhật hàng ngày.',
        'home.services.tools.title': 'Công cụ giao dịch',
        'home.services.tools.desc': 'Cung cấp các công cụ hỗ trợ giao dịch hiệu quả và quản lý rủi ro.',
        'home.testimonials.title': 'Khách hàng nói gì',
        'home.testimonials.subtitle': 'Những phản hồi từ cộng đồng trader Việt Nam',
        'home.testimonials.user1.name': 'Nguyễn Văn A',
        'home.testimonials.user1.role': 'Trader 3 năm',
        'home.testimonials.user1.comment': 'K-Network giúp tôi tìm được sàn forex uy tín và học được nhiều kiến thức quý giá. Từ một người mới bắt đầu, giờ tôi đã có thể giao dịch tự tin.',
        'home.testimonials.user2.name': 'Trần Thị B',
        'home.testimonials.user2.role': 'Nhà đầu tư crypto',
        'home.testimonials.user2.comment': 'Thông tin trên K-Network rất chính xác và cập nhật. Tôi đã tránh được nhiều rủi ro nhờ những đánh giá chi tiết về các sàn giao dịch.',
        'home.testimonials.user3.name': 'Lê Văn C',
        'home.testimonials.user3.role': 'Trader chuyên nghiệp',
        'home.testimonials.user3.comment': 'Là một trader có kinh nghiệm, tôi đánh giá cao chất lượng phân tích thị trường và tin tức trên K-Network. Rất hữu ích cho việc ra quyết định giao dịch.',
        'home.faq.title': 'Câu hỏi thường gặp',
        'home.faq.subtitle': 'Giải đáp những thắc mắc phổ biến',
        'home.faq.q1': 'K-Network có phải là sàn giao dịch không?',
        'home.faq.a1': 'Không, K-Network không phải là sàn giao dịch. Chúng tôi là nền tảng cung cấp thông tin, đánh giá và so sánh các sàn giao dịch uy tín.',
        'home.faq.q2': 'Thông tin trên K-Network có đáng tin cậy không?',
        'home.faq.a2': 'Có, tất cả thông tin trên K-Network đều được kiểm chứng từ các nguồn uy tín và cập nhật thường xuyên.',
        'home.faq.q3': 'Tôi có thể học giao dịch forex/crypto ở đâu?',
        'home.faq.a3': 'Bạn có thể học giao dịch thông qua các bài viết kiến thức, khóa học và tài liệu giáo dục được cung cấp miễn phí trên K-Network.',
        'home.faq.q4': 'Làm thế nào để chọn sàn giao dịch phù hợp?',
        'home.faq.a4': 'Chúng tôi cung cấp bộ tiêu chí đánh giá chi tiết để giúp bạn chọn sàn giao dịch phù hợp với nhu cầu và mục tiêu đầu tư.',
        'home.contact.title': 'Liên hệ với chúng tôi',
        'home.contact.subtitle': 'Hãy để lại thông tin, chúng tôi sẽ liên hệ lại trong thời gian sớm nhất',
        'home.contact.form.name': 'Họ và tên',
        'home.contact.form.email': 'Email',
        'home.contact.form.phone': 'Số điện thoại',
        'home.contact.form.message': 'Nội dung',
        'home.contact.form.submit': 'Gửi tin nhắn',
        'home.contact.info.title': 'Thông tin liên hệ',
        'home.contact.info.address': 'Địa chỉ: Vinh, Việt Nam',
        'home.contact.info.email': 'Email: business@k-network.io',
        'home.contact.info.phone': 'Điện thoại: +84 123 456 789',
        'home.contact.info.workingHours': 'Giờ làm việc: Thứ 2 - Thứ 6, 8:00 - 17:00',

        // News page
        'news.title': 'Tin Tức Forex Mới Nhất',
        'news.subtitle': 'Cập nhật những tin tức mới nhất về thị trường forex, phân tích kỹ thuật và cơ bản',
        'news.searchPlaceholder': 'Tìm kiếm tin tức...',
        'news.technical': 'Phân tích kỹ thuật',
        'news.fundamental': 'Phân tích cơ bản',
        'news.market': 'Tin tức thị trường',
        'news.newsletter.title': 'Đăng ký nhận tin tức',
        'news.newsletter.subtitle': 'Nhận tin tức forex mới nhất qua email',
        'news.newsletter.placeholder': 'Nhập email của bạn',
        'news.newsletter.button': 'Đăng ký',

        // Knowledge page
        'knowledge.title': 'Kiến Thức Forex',
        'knowledge.subtitle': 'Học hỏi từ cơ bản đến nâng cao về thị trường forex. Xây dựng nền tảng kiến thức vững chắc để giao dịch thành công.',
        'knowledge.articles': 'Bài viết',
        'knowledge.categories': 'Chuyên mục',
        'knowledge.searchPlaceholder': 'Tìm kiếm kiến thức...',
        'knowledge.basic': 'Kiến thức cơ bản',
        'knowledge.technical': 'Phân tích kỹ thuật',
        'knowledge.fundamental': 'Phân tích cơ bản',
        'knowledge.risk': 'Quản lý rủi ro',
        'knowledge.psychology': 'Tâm lý giao dịch',
        'knowledge.strategy': 'Chiến lược giao dịch',
        'knowledge.tools': 'Công cụ giao dịch',
        'knowledge.level.basic': 'Cơ bản',
        'knowledge.level.intermediate': 'Trung cấp',
        'knowledge.level.advanced': 'Nâng cao',
        'knowledge.notFound.title': 'Không tìm thấy kiến thức',
        'knowledge.notFound.subtitle': 'Thử thay đổi từ khóa tìm kiếm hoặc chọn chuyên mục khác',
        'knowledge.related': 'Bài viết liên quan',

        // Footer
        'footer.about': 'Về chúng tôi',
        'footer.contact': 'Liên hệ',
        'footer.policy': 'Chính sách',
        'footer.description': 'Cung cấp thông tin chính xác và cập nhật về thị trường forex',
        'footer.forex': 'Sàn Forex',
        'footer.crypto': 'Sàn Crypto',
        'footer.news': 'Tin Tức',
        'footer.knowledge': 'Kiến Thức',
        'footer.rights': 'Tất cả quyền được bảo lưu.',
        'footer.copyright': '© 2024 K-Network. Tất cả quyền được bảo lưu.',
        'footer.sitemap.title': 'Sitemap',
        'footer.sitemap.home': 'Trang chủ',
        'footer.sitemap.forex': 'Sàn Forex',
        'footer.sitemap.crypto': 'Sàn Crypto',
        'footer.sitemap.about': 'Chúng Tôi',
        'footer.sitemap.contact': 'Liên Hệ',
        'footer.legal.title': 'Pháp lý',
        'footer.legal.affiliate': 'Affiliate Disclosure',
        'footer.legal.risk': 'Risk Warning',
        'footer.legal.privacy': 'Privacy',
        'footer.legal.terms': 'Terms',
        'footer.socials.title': 'Socials',
        'footer.socials.telegram': 'Telegram',
        'footer.socials.youtube': 'YouTube',
        'footer.socials.facebook': 'Facebook',

        // Broker details
        'broker.description': 'Mô tả',
        'broker.features': 'Tính năng chính',
        'broker.pros': 'Ưu điểm',
        'broker.cons': 'Nhược điểm',
        'broker.tradingInfo': 'Thông tin giao dịch',
        'broker.platforms': 'Nền tảng giao dịch',
        'broker.instruments': 'Sản phẩm giao dịch',
        'broker.companyInfo': 'Thông tin công ty',
        'broker.founded': 'Thành lập',
        'broker.headquarters': 'Trụ sở chính',
        'broker.languages': 'Ngôn ngữ hỗ trợ',
        'broker.support': 'Hỗ trợ khách hàng',
        'broker.paymentMethods': 'Phương thức thanh toán',
        'broker.quickInfo': 'Thông tin nhanh',
        'broker.leverage': 'Đòn bẩy',

        // Settings
        'settings.language': 'Ngôn ngữ',
        'settings.theme': 'Giao diện',
        'settings.theme.light': 'Sáng',
        'settings.theme.dark': 'Tối',
        'settings.theme.auto': 'Tự động',

        // Crypto Brokers
        'crypto.title': 'Sàn Giao Dịch Cryptocurrency Tốt Nhất',
        'crypto.subtitle': 'So sánh và chọn sàn giao dịch cryptocurrency phù hợp nhất với nhu cầu của bạn',
        'crypto.searchPlaceholder': 'Tìm kiếm sàn giao dịch hoặc coin...',
        'crypto.sortByRating': 'Đánh giá cao nhất',
        'crypto.sortByName': 'Tên A-Z',
        'crypto.visit': 'Truy cập',
        'crypto.viewDetails': 'Chi tiết',
        'crypto.features': 'Tính năng chính',
        'crypto.tradingFees': 'Phí giao dịch',
        'crypto.minDeposit': 'Nạp tối thiểu',
        'crypto.regulation': 'Giấy phép',
        'crypto.supportedCoins': 'Coin hỗ trợ',
        'crypto.others': 'khác',
        'crypto.notFound.title': 'Không tìm thấy sàn giao dịch',
        'crypto.notFound.subtitle': 'Thử tìm kiếm với từ khóa khác',
        'crypto.newsletter.title': 'Nhận thông tin sàn giao dịch mới nhất',
        'crypto.newsletter.subtitle': 'Đăng ký để nhận thông tin về các sàn giao dịch cryptocurrency mới và cập nhật',
        'crypto.newsletter.placeholder': 'Nhập email của bạn',
        'crypto.newsletter.button': 'Đăng ký',

        'crypto.backToList': 'Quay lại danh sách sàn',
        'crypto.notFound.broker': 'Không tìm thấy sàn giao dịch',
        'crypto.detailedInfo': 'Thông tin chi tiết',
        'crypto.pros': 'Ưu điểm',
        'crypto.cons': 'Nhược điểm',
        'crypto.security': 'Bảo mật',
        'crypto.paymentMethods': 'Phương thức thanh toán',
        'crypto.customerSupport': 'Hỗ trợ khách hàng',
        'crypto.additionalInfo': 'Thông tin khác',
        'crypto.headquarters': 'Trụ sở',
        'crypto.founded': 'Năm thành lập',
        'crypto.tradingVolume': 'Khối lượng giao dịch',
        'crypto.mobileApp': 'Mobile App',
        'crypto.apiSupport': 'API Support',
        'crypto.yes': 'Có',
        'crypto.no': 'Không',
        'crypto.quickInfo': 'Thông tin nhanh',
        'crypto.companyInfo': 'Thông tin công ty',
        'crypto.tradingInfo': 'Thông tin giao dịch',


    },
    en: {
        // Navigation
        'nav.forex': 'Forex',
        'nav.news': 'Tin Tức',
        'nav.knowledge': 'Kiến Thức',
        'nav.cryptoBrokers': 'Crypto Brokers',
        'nav.joinTelegram': 'Tham gia Telegram',


        // Common
        'common.back': 'Back',
        'common.readMore': 'Read More',
        'common.search': 'Search',
        'common.filter': 'Filter',
        'common.sort': 'Sort',
        'common.category': 'Category',
        'common.all': 'All',
        'common.readTime': 'min',
        'common.previous': 'Previous',
        'common.next': 'Next',
        'common.page': 'Page',
        'common.of': 'of',
        'common.showing': 'Showing',
        'common.to': 'to',
        'common.items': 'items',

        // Home page
        'home.title': 'Top Forex Brokers',
        'home.subtitle': 'Discover the best forex brokers with detailed reviews, feature comparisons and direct registration links',
        'home.searchPlaceholder': 'Search forex brokers...',
        'home.sortByRating': 'Highest Rating',
        'home.sortByName': 'Name A-Z',
        'home.visit': 'Visit',
        'home.viewDetails': 'View Details',
        'home.regulation': 'Regulation',
        'home.minDeposit': 'Min Deposit',
        'home.spread': 'Spread',
        'home.noBrokersFound': 'No forex brokers found',
        'home.tryDifferentKeywords': 'Try searching with different keywords',
        'home.welcome': 'Welcome to K-Network',
        'home.heroTitle': 'Financial Platform',
        'home.heroTitleHighlight': 'leading',
        'home.heroSubtitle': 'Discover the forex and cryptocurrency world with accurate information, detailed reviews, and effective trading tools',
        'home.exploreForex': 'Explore Forex',
        'home.exploreCrypto': 'Explore Crypto',
        'home.stats.forexBrokers': 'Forex Brokers',
        'home.stats.cryptoBrokers': 'Crypto Brokers',
        'home.stats.articles': 'Articles',
        'home.stats.users': 'Users',
        'home.features.forexTitle': 'Trusted Forex Brokers',
        'home.features.forexDesc': 'Discover the best forex brokers with detailed reviews, feature comparisons and direct registration links',
        'home.features.cryptoTitle': 'Best Cryptocurrency Exchanges',
        'home.features.cryptoDesc': 'Compare and choose the best cryptocurrency exchange that suits your needs',
        'home.features.newsTitle': 'Latest Forex News',
        'home.features.newsDesc': 'Get the latest forex market news, technical and fundamental analysis',
        'home.features.knowledgeTitle': 'Forex Knowledge',
        'home.features.knowledgeDesc': 'Learn from basic to advanced about the forex market. Build a solid knowledge foundation for successful trading.',
        'home.features.exploreNow': 'Explore Now',
        'home.whyChoose.title': 'Why Choose K-Network?',
        'home.whyChoose.reliable.title': 'Reliable Information',
        'home.whyChoose.reliable.desc': 'Data is updated regularly and verified from trusted sources',
        'home.whyChoose.fast.title': 'Fast Updates',
        'home.whyChoose.fast.desc': 'Market information and broker reviews are updated in real-time',
        'home.whyChoose.community.title': 'Large Community',
        'home.whyChoose.community.desc': 'Support from experienced traders and financial experts in the community',
        'home.cta.title': 'Ready to start your trading journey?',
        'home.cta.subtitle': 'Join thousands of successful traders with K-Network',
        'home.cta.startForex': 'Start with Forex',
        'home.cta.exploreCrypto': 'Explore Crypto',
        'home.about.title': 'About K-Network',
        'home.about.subtitle': 'Who are we and why should you trust us?',
        'home.about.description': 'K-Network is the leading financial platform in Vietnam, specializing in providing accurate and objective information, reviews, and comparisons of reputable forex and cryptocurrency exchanges. With over 5 years of experience in the financial industry, we commit to bringing you the most accurate and reliable information.',
        'home.about.mission': 'Our Mission',
        'home.about.missionDesc': 'Help Vietnamese people access the global financial market safely and efficiently through the provision of reliable information and trading tools.',
        'home.about.vision': 'Vision',
        'home.about.visionDesc': 'Become the number one financial platform in Vietnam, trusted by millions of investors.',
        'home.services.title': 'Our Services',
        'home.services.subtitle': 'Everything you need to start your trading journey',
        'home.services.brokerReview.title': 'Broker Review',
        'home.services.brokerReview.desc': 'Detailed reviews and comparisons of reputable forex, crypto exchanges with transparent information.',
        'home.services.education.title': 'Financial Education',
        'home.services.education.desc': 'Courses from basic to advanced, helping you build a solid knowledge foundation.',
        'home.services.analysis.title': 'Market Analysis',
        'home.services.analysis.desc': 'Daily updates of news, technical and fundamental analysis.',
        'home.services.tools.title': 'Trading Tools',
        'home.services.tools.desc': 'Providing effective trading tools and risk management.',
        'home.testimonials.title': 'What Our Customers Say',
        'home.testimonials.subtitle': 'Customer feedback from the Vietnamese trading community',
        'home.testimonials.user1.name': 'Nguyen Quoc Huy',
        'home.testimonials.user1.role': 'Trader 3 years',
        'home.testimonials.user1.comment': 'K-Network helped me find a reputable forex exchange and learn valuable knowledge. From a beginner, I can now trade confidently.',
        'home.testimonials.user2.name': 'Tran Tuan Anh',
        'home.testimonials.user2.role': 'Crypto investor',
        'home.testimonials.user2.comment': 'The information on K-Network is very accurate and up-to-date. I have avoided many risks thanks to detailed reviews of exchanges.',
        'home.testimonials.user3.name': 'Le Anh',
        'home.testimonials.user3.role': 'Professional trader',
        'home.testimonials.user3.comment': 'As an experienced trader, I highly value the market analysis and news quality on K-Network. Very helpful for making trading decisions.',
        'home.faq.title': 'Frequently Asked Questions',
        'home.faq.subtitle': 'Answering common questions',
        'home.faq.q1': 'Is K-Network a trading platform?',
        'home.faq.a1': 'No, K-Network is not a trading platform. We are a platform providing information, reviews, and comparisons of reputable trading platforms.',
        'home.faq.q2': 'Is the information on K-Network reliable?',
        'home.faq.a2': 'Yes, all information on K-Network is verified from trusted sources and updated regularly.',
        'home.faq.q3': 'Where can I learn forex/crypto trading?',
        'home.faq.a3': 'You can learn trading through knowledge articles, courses, and educational materials provided for free on K-Network.',
        'home.faq.q4': 'How do I choose the right exchange?',
        'home.faq.a4': 'We provide detailed evaluation criteria to help you choose an exchange that suits your needs and investment goals.',
        'home.contact.title': 'Contact Us',
        'home.contact.subtitle': 'Leave your information, we will contact you as soon as possible',
        'home.contact.form.name': 'Full Name',
        'home.contact.form.email': 'Email',
        'home.contact.form.phone': 'Phone Number',
        'home.contact.form.message': 'Message',
        'home.contact.form.submit': 'Send Message',
        'home.contact.info.title': 'Contact Information',
        'home.contact.info.address': 'Address: Vinh, Vietnam',
        'home.contact.info.email': 'Email: business@k-network.io',
        'home.contact.info.phone': 'Phone: +84 123 456 789',
        'home.contact.info.workingHours': 'Working Hours: Monday - Friday, 8:00 - 17:00',

        // News page
        'news.title': 'Latest Forex News',
        'news.subtitle': 'Get the latest forex market news, technical and fundamental analysis',
        'news.searchPlaceholder': 'Search news...',
        'news.technical': 'Technical Analysis',
        'news.fundamental': 'Fundamental Analysis',
        'news.market': 'Market News',
        'news.newsletter.title': 'Subscribe to News',
        'news.newsletter.subtitle': 'Get latest forex news via email',
        'news.newsletter.placeholder': 'Enter your email',
        'news.newsletter.button': 'Subscribe',

        // Knowledge page
        'knowledge.title': 'Forex Knowledge',
        'knowledge.subtitle': 'Learn from basic to advanced about the forex market. Build a solid knowledge foundation for successful trading.',
        'knowledge.articles': 'Articles',
        'knowledge.categories': 'Categories',
        'knowledge.searchPlaceholder': 'Search knowledge...',
        'knowledge.basic': 'Basic Knowledge',
        'knowledge.technical': 'Technical Analysis',
        'knowledge.fundamental': 'Fundamental Analysis',
        'knowledge.risk': 'Risk Management',
        'knowledge.psychology': 'Trading Psychology',
        'knowledge.strategy': 'Trading Strategy',
        'knowledge.tools': 'Trading Tools',
        'knowledge.level.basic': 'Basic',
        'knowledge.level.intermediate': 'Intermediate',
        'knowledge.level.advanced': 'Advanced',
        'knowledge.notFound.title': 'No knowledge found',
        'knowledge.notFound.subtitle': 'Try changing search keywords or select different category',
        'knowledge.related': 'Related Articles',

        // Footer
        'footer.about': 'About Us',
        'footer.contact': 'Contact',
        'footer.policy': 'Policy',
        'footer.description': 'Providing accurate and up-to-date information about the forex market',
        'footer.forex': 'Forex Brokers',
        'footer.crypto': 'Crypto Brokers',
        'footer.news': 'News',
        'footer.knowledge': 'Knowledge',
        'footer.rights': 'All rights reserved.',
        'footer.copyright': '© 2024 K-Network. All rights reserved.',
        'footer.sitemap.title': 'Sitemap',
        'footer.sitemap.home': 'Home',
        'footer.sitemap.forex': 'Forex Brokers',
        'footer.sitemap.crypto': 'Crypto Brokers',
        'footer.sitemap.about': 'About Us',
        'footer.sitemap.contact': 'Contact',
        'footer.legal.title': 'Legal',
        'footer.legal.affiliate': 'Affiliate Disclosure',
        'footer.legal.risk': 'Risk Warning',
        'footer.legal.privacy': 'Privacy',
        'footer.legal.terms': 'Terms',
        'footer.socials.title': 'Socials',
        'footer.socials.telegram': 'Telegram',
        'footer.socials.youtube': 'YouTube',
        'footer.socials.facebook': 'Facebook',

        // Broker details
        'broker.description': 'Description',
        'broker.features': 'Key Features',
        'broker.pros': 'Pros',
        'broker.cons': 'Cons',
        'broker.tradingInfo': 'Trading Information',
        'broker.platforms': 'Trading Platforms',
        'broker.instruments': 'Trading Instruments',
        'broker.companyInfo': 'Company Information',
        'broker.founded': 'Founded',
        'broker.headquarters': 'Headquarters',
        'broker.languages': 'Supported Languages',
        'broker.support': 'Customer Support',
        'broker.paymentMethods': 'Payment Methods',
        'broker.quickInfo': 'Quick Info',
        'broker.leverage': 'Leverage',

        // Settings
        'settings.language': 'Language',
        'settings.theme': 'Theme',
        'settings.theme.light': 'Light',
        'settings.theme.dark': 'Dark',
        'settings.theme.auto': 'Auto',

        // Crypto Brokers
        'crypto.title': 'Best Cryptocurrency Exchanges',
        'crypto.subtitle': 'Compare and choose the best cryptocurrency exchange that suits your needs',
        'crypto.searchPlaceholder': 'Search exchanges or coins...',
        'crypto.sortByRating': 'Highest Rating',
        'crypto.sortByName': 'Name A-Z',
        'crypto.visit': 'Visit',
        'crypto.viewDetails': 'Details',
        'crypto.features': 'Key Features',
        'crypto.tradingFees': 'Trading Fees',
        'crypto.minDeposit': 'Min Deposit',
        'crypto.regulation': 'Regulation',
        'crypto.supportedCoins': 'Supported Coins',
        'crypto.others': 'others',
        'crypto.notFound.title': 'No exchanges found',
        'crypto.notFound.subtitle': 'Try searching with different keywords',
        'crypto.newsletter.title': 'Get Latest Exchange Updates',
        'crypto.newsletter.subtitle': 'Subscribe to receive information about new cryptocurrency exchanges and updates',
        'crypto.newsletter.placeholder': 'Enter your email',
        'crypto.newsletter.button': 'Subscribe',

        'crypto.backToList': 'Back to Exchange List',
        'crypto.notFound.broker': 'Exchange not found',
        'crypto.detailedInfo': 'Detailed Information',
        'crypto.pros': 'Pros',
        'crypto.cons': 'Cons',
        'crypto.security': 'Security',
        'crypto.paymentMethods': 'Payment Methods',
        'crypto.customerSupport': 'Customer Support',
        'crypto.additionalInfo': 'Additional Info',
        'crypto.headquarters': 'Headquarters',
        'crypto.founded': 'Founded',
        'crypto.tradingVolume': 'Trading Volume',
        'crypto.mobileApp': 'Mobile App',
        'crypto.apiSupport': 'API Support',
        'crypto.yes': 'Yes',
        'crypto.no': 'No',
        'crypto.quickInfo': 'Quick Info',
        'crypto.companyInfo': 'Company Information',
        'crypto.tradingInfo': 'Trading Information',


    }
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguageState] = useState<Language>('en')
    const [mounted, setMounted] = useState(false)

    useEffect(() => {
        setMounted(true)
        // Lấy language từ localStorage, mặc định là 'en'
        const savedLanguage = localStorage.getItem('language') as Language
        if (savedLanguage) {
            setLanguageState(savedLanguage)
        } else {
            // Nếu chưa có trong localStorage, set mặc định là 'en'
            localStorage.setItem('language', 'en')
        }
    }, [])

    const setLanguage = (lang: Language) => {
        setLanguageState(lang)
        localStorage.setItem('language', lang)
    }

    const t = (key: string): string => {
        return translations[language][key as keyof typeof translations[typeof language]] || key
    }

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t, mounted }}>
            {children}
        </LanguageContext.Provider>
    )
}

export function useLanguage() {
    const context = useContext(LanguageContext)
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider')
    }
    return context
} 